export const topics = [
  {
    id: 'breakfast',
    name: '减脂早餐',
    hashtag: '#减脂早餐这样吃',
    heat: '98.3k',
    growth: '86.7%',
    gap: '高',
    gapValue: 92,
    color: '#ff4650',
    angle: '5 分钟高蛋白早餐搭配，饱腹不发胖',
    title: '减脂期别再只吃水煮菜',
    hook: '你不是瘦不下来，是第一顿就吃错了。',
    retention: '反常识否定 + 结果延迟 + 三步清单',
    metrics: ['82.4w', '3.1w', '9.6w'],
    chart: [18, 22, 28, 35, 41, 47, 56, 66, 74, 69, 69, 68, 73, 82, 98],
  },
  {
    id: 'plateau',
    name: '体重平台期',
    hashtag: '#体重不掉先别慌',
    heat: '72.1k',
    growth: '63.2%',
    gap: '中',
    gapValue: 64,
    color: '#ff8a2a',
    angle: '体重平台期的 3 个原因自查 + 调整方案',
    title: '七天没掉秤，可能是好事',
    hook: '体重没变，不代表你的脂肪没有在掉。',
    retention: '焦虑止损 + 原因排查 + 对比验证',
    metrics: ['66.8w', '2.4w', '7.8w'],
    chart: [16, 19, 24, 29, 38, 43, 41, 49, 55, 54, 60, 63, 65, 68, 72],
  },
  {
    id: 'dinner',
    name: '低卡晚餐',
    hashtag: '#低卡晚餐公式',
    heat: '58.6k',
    growth: '48.9%',
    gap: '中',
    gapValue: 58,
    color: '#31bd87',
    angle: '万能低卡晚餐公式，一周不重样',
    title: '晚餐这样搭，吃饱也能掉秤',
    hook: '不用饿肚子，记住这个一拳一掌公式。',
    retention: '公式记忆 + 视觉演示 + 一周菜单',
    metrics: ['53.2w', '1.9w', '8.2w'],
    chart: [11, 16, 20, 19, 27, 31, 36, 42, 40, 43, 48, 46, 51, 54, 59],
  },
]

export const navItems = [
  ['overview', '趋势总览', 'trend'],
  ['topics', '热门话题', 'flame'],
  ['scripts', '脚本拆解', 'script'],
  ['ideas', '选题库', 'bulb'],
  ['tasks', '采集任务', 'briefcase'],
]

export const timeline = [
  ['0–3s', '爆点开头', '反常识否定 + 结果悬念'],
  ['4–12s', '痛点放大', '常见误区 + 真实困扰'],
  ['13–28s', '方法演示', '步骤拆解 + 细节展示'],
  ['29–36s', '结果回收', '效果对比 + 行动引导'],
]
